// <auto-generated />
namespace Sample_BugTracker.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class FixproblemSqlDateTimeMinValueandDateTimeMinValue : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixproblemSqlDateTimeMinValueandDateTimeMinValue));
        
        string IMigrationMetadata.Id
        {
            get { return "201804172139003_Fix problem SqlDateTime.MinValue and DateTime.MinValue"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
